### ISSUE TITLE
Dependencies pinned too stringently

### ISSUE THREAD

**Issue by moggers87** [hyde/hyde#281]
For example, Jinja2 is pinned to 2.7.3. If my system has 2.7.2 or 2.7.4 (supposing that it existed) then I would need GCC to install Hyde.

Instead of pinning to a specific patch level, something like `package=>2.7,<2.8` would allow more flexibility without breaking Hyde due to API changes.

**Comment by llonchj** [comment]
@moggers87 Please, submit a merge request with dependencies set to a minor level

**Comment by jonafato** [comment]
Hyde is really an application rather than a library, so it makes sense to have pinned dependencies. See [this post](https://caremad.io/2013/07/setup-vs-requirement/) for a detailed explanation about the differences.

@moggers87: Generally, the solution to the problem you're experiencing is [virtualenv](https://virtualenv.readthedocs.org/en/latest/). Even if Hyde becomes more flexible with regard to dependencies, it's only a matter of time until another application introduces new dependency conflicts. Using separate virtual environments for each of your Python applications will ensure that these kinds of issues don't crop up again and again.

That said, there's little downside to allowing Hyde's dependencies to vary within minor versions. There's always the possibility of bugs being introduced with library updates, but as long as Hyde and its dependencies are being actively developed, upgrading dependencies shouldn't be a big issue.

**Comment by llonchj** [comment]
@jonafato you're right! That was my take when i set strict dependency version but also agree on the fact that some users might have version issues.
